package main;

public enum PossibleUpdates {
	//Landlebewesen,wasserlebewesen,Fleischfresser,Pflanzenfresser,endoskelett,exoskelett, r stratege, k stratege, dünnes fell, dickes fell
	LANDSPECIES,WATESPECIES,CARNIVORE,HERBIVORE,ENDOSKELETON,EXOSKELETON
	,RSTRATEGIST,KSTRATEGIST,THINFUR,THICKFUR,WINGS,FLYWINGS,BATTLEWINGS
	,CENTRALNERVSYSTEM,GILLS,BRAIN,FRONTALLOBE,LIMBICSYSTEM,ULTRASAOUND,EYES,LEATHERSKIN,
	SWEATGLAND,FATLAYER,FURLESSSKIN,BETTERMUSCLES,DRAGONSCALE,COMPLEXTENDONSTRUCTUR,
	CLAWARM,HANDARM,FOOTARM,EXTREMITYARM,HANDLEG,FOOTLEG,FINLEG,EXTREMITYLEG,
	GENITAL,SECONDGENITAL,TAIL,DECOTAIL,FIGHTTAIL,GYMNASTICTAIL,SEXUALPROCREATION,
	POLYGAMY,MONOGAMY,PACKANIMAL,MAVERICK,LANGUAGE,LOGIC,THUMBS,FIREMAKING,SPITFIREDRAGON,
	PHEROMONS,KIDSCHEME,SETTLE;
}
