package main;

public enum PossibleUpdates {
	//Landlebewesen,wasserlebewesen,Fleischfresser,Pflanzenfresser,endoskelett,exoskelett, r stratege, k stratege, dünnes fell, dickes fell
	LANDSPECIES,WATESPECIES,CARNIVORE,HERBIVORE,ENDOSKELETON,EXOSKELETON
	,RSTRATEGIST,KSTRATEGIST,THINFUR,THICKFUR,WINGS,FLYWINGS,BATTLEWINGS
	,CENTRALNERVSYSTEM,BRAIN,FRONTALLOBE,LIMBICSYSTEM,ULTRASAOUND,EYES,LEATHERSKIN,
	SWEATGLAND,FATLAYER,FURLESSSKIN,BETTERMUSCLES,DRAGONSCALE,COMPLEXTENDONSTRUCTUR;
}
